[임루트] 온보드 - 학습 테스트, 단위 테스트
woowacourse/java-calculator pull request #19
Opened 2020-02-07 08:38 UTC by p-vibe

안녕하세요, 임루트라고합니다.
리뷰 잘 부탁드리겠습니다!
감사합니다.

2020-02-07 14:21 UTC, hongsii requested changes
안녕하세요~ 임루트 리뷰를 맡게 된 홍시입니다.
객체별로 역할을 잘 분리하셨네요 👍 
몇 가지 피드백 드렸으니 반영해주세요~

2020-02-07 14:21 UTC, hongsii commented on src/main/java/Application.java
> +        outputView.showCalculateResult(result);
역할 분리 👍

2020-02-07 14:21 UTC, hongsii commented on src/main/java/view/InputView.java
> +        if (sentence.isEmpty()) {
아래와 같이 작성해도 좋을 것 같아요~

``` java
return !sentence.isEmpty();
```

2020-02-07 14:21 UTC, hongsii commented on src/main/java/domain/Calculator.java
> +                    throw new InvalidParameterException("not allowed ");
새로운 연산자가 추가될 때 마다 switch문 및 연산 메서드를 추가해야 합니다. `calculate()` 메서드가 길어져 로직이 점점 복잡해질 수 있습니다. 
아래와 같은 인터페이스로 추상화해 분기문을 제거해보면 어떨까요?

``` java
public interface Operation {
    int operate(int number1, int number2);
}
```

2020-02-07 14:21 UTC, hongsii commented on src/main/java/view/InputView.java
> +        return new NumberSentence(numbers, operators);
`InputView` 는 사용자의 입력만 담당하고, `NumberSentence` 가 스스로 객체를 생성하도록 역할을 위임해도 좋을 것 같아요.

2020-02-08 13:54 UTC, p-vibe commented on src/main/java/view/InputView.java
> +        if (sentence.isEmpty()) {
수정했습니다!

2020-02-08 14:04 UTC, p-vibe commented on src/main/java/domain/Calculator.java
> +                    throw new InvalidParameterException("not allowed ");
한 번 Operation 인터페이스를 활용하여 수정해봤는데, 홍시님이 얘기해주신 것을 제가 잘 이해했는지 모르겠습니다...^^;; 

이 부분과 관련하여 질문이 있는데요, 이렇게 수정했을 때
1. 새로운 연산자가 추가될 때마다 해당 연산자를 분기처리하는 건 여전하고, Operation객체를 구현해주는 클래스(ex: AddOperation)를 추가해줘야 할 것 같은데요. 이렇게 되면 새로운 연산자 추가에 따라 로직이 복잡해지는 문제(분기처리 추가)를 해결하진 못한 것 같고, Class파일이 많아지기 때문에 파일 구조도 복잡해질 수 있을 것 같습니다. 그래서 제가 홍시님의 말씀을 잘 이해하지 못한건가 하는 생각이 들었습니다...! 제가 잘 이해한 것이 맞는 지, 아니라면 조금 더 설명해주시면 감사하겠습니다!

2. switch 문과 관련하여 질문이 있습니다. 우아한테크코스의 사전과정인 프리코스에서, else나 switch를 쓰지 말고 다음과 같이 if만 써서 분기처리하는 게 좋다는 피드백이 있었습니다. 

```
if (SomeLogic) {
    return Something;
}
```
switch 문 자체에 어떤 문제가 있는것인지, 아니면 홍시님이 위에서 피드백을 해주셨듯 분기 자체를 하지 말아야 하는 것인지 궁금합니다. 만약 분기 자체를 하지 말아야 하는 것이라면, 입력에 따라 어떤 함수를 호출할 지 결정하는 로직을 어떻게 만들어야 하는지 모르겠어서 알려주시면 감사하겠습니다!

2020-02-08 14:12 UTC, p-vibe commented on src/main/java/view/InputView.java
> +        return new NumberSentence(numbers, operators);
InputView가 자신의 관심사가 아닌 NumberSentence 생성을 담당하고 있었네요!
이를 해결하기 위하여, 현재 InputView가 NumberSentenceTranslator 인터페이스에 의존하게 하고, NumberSentenceTranslator가 NumberSentence를 생성하는 책임을 담당하게 처리했는데 잘 한건지 모르겠습니다...
그래서 다음과 같이 만들어보기도 했는데 어떤 게 나은건지, 혹은 제 3의 방법이 있는 것인지 알려주시면 감사하겠습니다!

```
public class NumberSentence {
    ...
    public static NumberSentence create(List<Integer> numbers, Queue<String> operators) {
        return new NumberSentence(numbers, operators);
    }
    ...
}
```

```
public class InputView {
    ...
    private NumberSentence buildNumberSentence(String sentence) {
    	...
    	return NumberSentence.create(numbers, operators);
    }
    ...
}
```

2020-02-09 05:21 UTC, hongsii commented on src/main/java/domain/Calculator.java
> +                    throw new InvalidParameterException("not allowed ");
이건 제가 피드백을 잘못 드렸습니다. 혼란을 드려 죄송합니다.. ㅠㅠ

말씀해주신 것처럼 **위 인터페이스만으론 분기문을 제거할 수 없습니다.**
위 피드백은 switch문이 문제가 아니라 추상화를 통해 매번 기호가 추가될 때 마다 분기문을 추가하지 않아도 되는 구조로 바꿔보라는 의미에서 드린 피드백이였습니다. (아래 드린 피드백을 진행하실 때에도 분기문은 사용하게 되실겁니다. 하지만, 지금처럼 매번 분기문이 추가되는 구조가 아닙니다.)

추가적으로 피드백을 드리자면 **추상화한 연산자와 연산자 기호를 연결하는 작업이 필요**합니다.
현재는 이 작업을 분기문으로 하고 있습니다. 그럼 기호가 추가될 때마다 분기문이 늘어나고, 추가된 분기문으로 메서드의 길이가 길어질수록 로직이 한 눈에 들어오지 않아  코드 분석이 힘들어 집니다.
(현재는 간단한 프로그램이라 위 내용이 와닿지 않을 수 있습니다.)

위 문제를 해결하려면 자바에서는 상수를 한 곳에 묶어서 관리하기 위해 만들어진 `Enum` 클래스를 사용해 연산자 기호와 연산을 묶어서 관리할 수 있습니다.
그리고 `Calculator` 클래스가 "입력된 값을 계산하는 역할" 외에도 "연산자를 선택하는 역할"까지 2가지 일을 하고 있습니다. 연산자를 선택하는 책임은 `Enum` 클래스를 만들어 책임 분리해보시면 좋을 듯 합니다.

몇 가지 참고할 링크드립니다! 
* [Java Enum 활용기](http://woowabros.github.io/tools/2017/07/10/java-enum-uses.html)
* [Anti-OOP : if 를 피하고 싶어서](http://redutan.github.io/2016/03/31/anti-oop-if)

혹시나 이해가 가지 않거나 궁금한 점이 있다면 언제든 DM으로 연락주세요! :)

2020-02-09 05:58 UTC, hongsii requested changes
피드백 반영을 잘 해주셨습니다!
추가적으로 피드백드렸으니, 확인하시고 반영해주세요 :)

2020-02-09 05:58 UTC, hongsii commented on src/main/java/view/InputView.java
> +    }
저는`NumberSentence` 생성자 또는 정적 팩토리 메서드에서 문자열 파싱을 통해 객체를 생성하는 책임을 가지면 좋을 것 같다고 생각했습니다.

`NumberSentenceTranslator` 와 같은 팩토리 클래스를 사용하신 것은 잘하셨습니다! 👍 
다만, 파싱된 파라미터만 받아서 인스턴스만 생성 하는 역할이라면 오히려 이 클래스가 불필요해보이며, 문자열을 파싱하는 것까지 해당 클래스로 옮기는 게 더 적절해보입니다.

그리고 인터페이스는 반드시 추상화가 가능한 경우에만 사용하는 게 좋습니다. 현재로썬 별다른 이유가 없다면 클래스로 변경해도 무방해보입니다.
* [impl-classes-are-evil](https://octoperf.com/blog/2016/10/27/impl-classes-are-evil/)

2020-02-09 05:58 UTC, hongsii commented on src/test/java/domain/CalculatorTest.java
> +class CalculatorTest {
예외 케이스도 테스트로 작성해보면 어떨까요?

2020-02-09 05:58 UTC, hongsii commented on src/main/java/domain/Calculator.java
> +        return new DivideOperation();
존재하지 않는 연산자여도 나누기 연산으로 실행되는 문제가 있습니다. 연산자를 찾을 수 없다면 예외를 발생시키는게 어떨까요?

2020-02-10 02:32 UTC, p-vibe commented on src/main/java/domain/Calculator.java
> +                    throw new InvalidParameterException("not allowed ");
아 이제 홍시님이 말씀해주신 게 어떤 이야기인지 이해된 것 같습니다! 자세히 말씀해주셔서 감사합니다..! 한 번  피드백해주신대로 고쳐봤는데, 확인해주시면 감사하겠습니다.

2020-02-10 02:43 UTC, p-vibe commented on src/main/java/view/InputView.java
> +    }
Translator라는 객체를 두는 것보다, static 으로 하는 게 더 깔끔한 것 같아 NumberSentence.newInstnace()로 바꿔봤습니다!

그런데 수정사항과 상관없이, 제가 최근 정말 궁금해하던 부분에 대해 피드백 주셔서 감사한 마음으로 다시 질문드립니다.
저는 최근 "**언제 인터페이스를 안쓰는가?**"에 대해 고민하고 있었습니다. 토비의 스프링이라는 책을 읽을 때, "모든 코드는 변한다. 따라서, 추상화해놓는 게 필요하다. 만약 구체적인 근거를 댈 수 없다면, 그냥 인터페이스로 만들고 구현해라" 라는 문구를 본 적이 있습니다.
저는 이제까지 그 "구체적인 근거"를 댈 수 없었고, 항상 인터페이스를 먼저 만들었습니다... 그러다보니 모든 코드가 인터페이스 화 됐으며, 제가 근거없이 기계적으로 인터페이스를 만드는 것 같다는 느낌을 받았습니다.
그런데 다른 좋은 코드들을 봐도, entity같은 클래스는 인터페이스가 없다는 걸 보면서, 모든 객체를 인터페이스화 하는 건 아닌것같다는 느낌이었습니다.

그래서 Impl-classes-are-evil이라는 포스트를 주셨을 때 너무 좋았습니다. 그런데, 이 포스트를 봤을 때 제가 이해하기로는 "impl이라는 문구는 어떤 의미를 주지 못하고, 바뀔 것이라고 충분히 예상되는 것들을 대상으로 인터페이스화하고, 클래스에 그 구현체에 어떠한 의미를 담아라"라고 이해했습니다.

이렇게 이해했을 때, 한가지 궁금점이 생겼습니다. 미션으로 다시 돌아와서, NumberSentenceTranslator가 현재 어떤 식으로 바뀔 지 예상은 안돼서 impl이라고 했지만, 구현 로직을 바꿔야 할 수도 있으니, 인터페이스화 하는 것이 의미있는 것 아닌가요?
만약 NumberSentenceTraslator를 클래스화했다면, 추후 "아 이건 앞으로 바뀔 가능성이 높다" 라고 판단이 바뀐 순간에, NumberSentenceTranslator가 사용되는 모든 곳을 찾아가며 인터페이스로 바꿔줘야 할 것 같습니다. 반면, NumberSentenceTranslator를 인터페이스로 만들고, NumberSentenceTranslatorImpl로 구현체를 만들었을 경우, NumberSentenceTranslatorImpl의 네이밍만 바꿔주고, 새로운 NumberSentenceTranslator를 구현한 후 di 설정만 바꿔주면 될 것 같습니다. 즉, 인터페이스화 하는 것이 장점이 있을 것 같습니다.

이 부분에 대해 어떻게 생각하시는 지 공유해주시면 저에게 큰 도움이 될 것 같습니다...!
감사합니다.

2020-02-10 02:44 UTC, p-vibe commented on src/test/java/domain/CalculatorTest.java
> +class CalculatorTest {
예외 케이스 테스트 추가했습니다!

2020-02-10 02:44 UTC, p-vibe commented on src/main/java/domain/Calculator.java
> +        return new DivideOperation();
추가했습니다!

2020-02-10 10:45 UTC, hongsii commented on src/main/java/domain/Operator.java
> +public enum Operator {
`Enum` 사용 💯

2020-02-10 10:45 UTC, hongsii commented on src/main/java/view/InputView.java
> +    }
저도 이 부분에 대해서 많은 고민을 했지만, 명쾌한 해답을 찾진 못했습니다. 다만, 제가 경험한 것을 어느 정도 선을 정했습니다. 그렇기 때문에 옳지 않은 방식일 수도 있기 때문에 감안해서 읽어주시면 감사하겠습니다!

----

저는 개발자의 통제 여부에 따라 인터페이스를 적용하는 기준이 달라진다고 생각합니다.
개발자가 통제할 수 없는 외부 시스템으로 모듈을 제공해야 한다면 인터페이스를 통해 결합도를 낮춰두면 추후 확장이 필요할 때 대응하기가 쉽습니다. (외부 시스템으로 한 번 노출된 클래스는 변경이 매우 힘듭니다...)

하지만, 개발자가 스스로 통제할 수 있는 영역은 확장 여부가 확실한 게 아니라면 인터페이스를 적용하지 않습니다. 확장 여부가 불명확한 클래스에 인터페이스를 적용하면 대부분이 인터페이스와 일대일로 구성되며, 확장되는 경우가 거의 없었습니다.  

개발을 하다 보면 대부분의 클래스가 생각보다 좁은 범위에서만 사용됩니다. 그래서 인터페이스를 적용하지 않은 상태에서 확장이 생겼을 때, IDE를 통해 통해 충분히 커버가 가능했습니다.
저는 오히려 일대일로 구성된 클래스에 새로운 메서드를 추가할 때 마다 인터페이스에 매번 메서드를 추가하는 자잘한 작업의 스트레스가 생각보다 더 컸습니다.

명확한 설계가 아니라면 당장 필요한 것만 구현하는 게 제일 좋다고 생각하며, 미리 걱정해 먼저 구현하다보면 오히려 오버엔지니어링이 되는 경우가 많았습니다. 
모든 설계는 트레이드 오프이며, 정답이 없기 때문에 다양한 경험을 통해서 본인만의 적절한 선을 찾으시면 좋을 것 같습니다 :)

2020-02-10 10:48 UTC, hongsii approved these changes
리팩토링을 잘 해주셨네요! 💯 
질문에 대해 답변을 달아두었으니, 확인해주세요~
요구사항을 만족하셔서 이번 단계는 여기서 머지하겠습니다 :)

2020-02-10 10:49 UTC, merged

2020-02-11 02:45 UTC, p-vibe commented
@hongsii 
홍시님, 지금 피드백 자세히 확인했습니다.
저에겐 정말 큰 도움이 됐습니다.
고민하던 부분에 대해서 어느정도 해결이 됐고, 홍시님이 말씀해주신 것에 공감이 갔습니다(특히 인터페이스 - impl관련).
정말 감사드립니다!!