[카프카] 코드리뷰 요청합니다.
woowacourse/java-calculator pull request #21
Opened 2020-02-07 08:40 UTC by include42

안녕하세요. 우아한테크코스 2기 카프카라고 합니다.

JUnit 관련하여 학습 테스트 및 단위 테스트 코드리뷰 요청드립니다.
부족한 부분 지적해 주시면 수정하도록 하겠습니다.

답변 주시면 확인하겠습니다. 
감사합니다.

2020-02-08 02:24 UTC, kang-hyungu requested changes
안녕하세요 카프카!
리뷰어 구구에요. 만나서 반가워요 👋
꼼꼼하게 주석 남긴 부분이 인상 깊네요
덕분에 어떤 의도로 작성한 코드인지 파악하기 좋았네요 👍 
그리고 추가로 메서드에 public 접근제어자는 언제 쓰면 좋을지 찾아보아요! (리팩토링 - 저자 마틴 파울러, p361 참고)

피드백 확인해보시고 궁금한 점 생기면 언제든 pr에 코멘트 남기시거나 dm 주세요

2020-02-08 02:24 UTC, kang-hyungu commented on src/main/java/calculator/Calculator.java
> +        Scanner scanner = new Scanner(System.in);
매번 새로운 Scanner 객체를 생성하는 것보다 처음 Calculator 객체가 생성됐을 때 한 번만 생성하도록 만드는 건 어떨까요?

2020-02-08 02:24 UTC, kang-hyungu commented on src/main/java/calculator/Calculator.java
> +        } catch (InputMismatchException e3) {
NumberFormatException 예외와 처리 방식이 동일하네요
코드 중복을 줄이면 코드가 더 읽기 쉬울거에요
```
catch (NumberFormatException | InputMismatchException e) 
```

2020-02-08 02:24 UTC, kang-hyungu commented on src/main/java/calculator/Calculator.java
> +        return inputString == null || inputString.equals("");
더 간략하게 줄일 수 있지 않을까요?
```suggestion
        return "".equals(inputString);
```

2020-02-08 02:24 UTC, kang-hyungu commented on src/main/java/calculator/Calculator.java
> +    public boolean validateString(String inputString) {
접근제어자를 public 대신 private으로 바꾸는게 좋겠어요

2020-02-08 02:24 UTC, kang-hyungu commented on src/main/java/calculator/Calculator.java
> +            throw e;
예외를 전달해주는 역할만 하네요
메서드에 throws ArithmeticException를 붙여주면 더 간결해지지 않을까요?

2020-02-08 02:24 UTC, kang-hyungu commented on src/test/java/study/StringTest.java
> +    void split2() {
테스트 메서드명도 의미를 알 수 있도록 만들어주는게 좋아요
어떤 테스트인지 메서드명이나 DisplayName 어노테이션으로 잘 작성해두면 협업하는 다른 동료가 테스트를 봤을 때 테스트 코드를 분석하지 않아도 어떤 테스트인지 쉽게 파악할 수 있어서 생산성을 높이는데 도움이 됩니다

2020-02-08 03:39 UTC, include42 commented
코멘트 감사합니다!! 말씀해주신 부분들을 수정해서 다시 PR 보내보겠습니다ㅎㅎ
접근제어자는 테스트코드 수행을 위해 잠시 바꿔두고 수정하지 않아 민망하네요ㅠㅠ 좋은 레퍼런스까지 남겨주셔서 다시 고민해볼 생각입니다!!

그리고 여쭤보고 싶은 것이 있었는데, 이렇게 문서화 주석을 모든 메서드에 촘촘히 달아두는 것은 (시간이 허락한다면) 꼭 해두는것이 좋은 것인가요? 
혹여나 너무 과한것은 아닐까 걱정될때가 있어서요ㅎㅎ 예를 들어 직관적인 메서드엔 달지 않아도 된다!! 같은 기준이 현업쪽에 있을까 싶어 질문드립니다!!

2020-02-10 00:28 UTC, kang-hyungu commented
주석을 달아두면 좋지만 필수로 강제하진 않아요
저는 주석보다 클래스명, 메서드명, 변수명으로 의미를 잘 전달할 수 있도록 이름을 잘 지으려고 하는 편이에요
글을 읽는 것처럼 코드를 쭉 읽어 나갈 수 있게 작성하면 주석 없이 충분히 의도를 전달 할 수 있어서요.
주석은 팀에서 협의해서 정하면 될 것 같네요. 팀바팀이라 보시면 됩니다 :)

2020-02-10 00:45 UTC, kang-hyungu approved these changes
피드백 반영 잘 하셨어요 👏 
몇 가지 추가 코멘트 남겼는데 다음 미션 진행할 때 참고하세요
코드 구현 하느라 수고하셨어요!

2020-02-10 00:45 UTC, kang-hyungu commented on src/main/java/calculator/Calculator.java
> +        Scanner scanner = new Scanner(System.in);
```suggestion
    private final static Scanner scanner = new Scanner(System.in);
```
static 변수로 바꾸는게 좋겠어요
메서드가 호출될 때마다 scanner 객체를 새로 만들거에요

2020-02-10 00:45 UTC, kang-hyungu commented on src/main/java/calculator/Calculator.java
> +            start();
예외만 발생시켜도 충분하지 않을까요?
예외가 발생할 때 프로그램 재시작을 계산기가 할 필요가 없어보이네요
Main 클래스에서 예외를 catch 해서 start() 메서드를 실행하도록 구현하면 코드 중복을 줄일 수 있을 것 같네요

2020-02-10 00:45 UTC, kang-hyungu commented on src/main/java/calculator/Calculator.java
> +        return scanner.nextLine().trim();
메서드는 한 가지 기능만 하도록 작성하는게 좋습니다
외부 입력 받는 기능만 처리 하고 trim으로 공백 제거는 따로 하는게 좋겠네요

2020-02-10 00:45 UTC, kang-hyungu commented on src/main/java/calculator/OperatorType.java
> +interface OperationMethod {
OperatorType에서만 사용할 의도라면 inner 클래스로 작성하는게 좋지 않을까요?
이펙티브 자바 3판 - 아이템 25 톱레벨 클래스는 한 파일에 하나만 담으라를 참고하세요

2020-02-10 00:45 UTC, kang-hyungu commented on src/main/java/calculator/OperatorType.java
> +            if (calculatorType.toString().equals(inputOperator)) {
객체지향 생활 체조
규칙 1: 한 메서드에 오직 한 단계의 들여쓰기만 한다.
stream을 활용하면 depth를 줄이기 수월할거에요

2020-02-10 00:45 UTC, kang-hyungu commented on src/main/java/calculator/OperatorType.java
> +    public static OperatorType findApplyToOperator(String inputOperator) throws IllegalArgumentException {
메서드명에 내부 구현 내용을 드러낼 필요는 없어보여요
보통 enum에서 상수값 찾아서 반환하는 메서드는 valueOf로 명명하는 경우가 많아요

2020-02-10 00:45 UTC, merged

2020-02-10 03:03 UTC, include42 commented on src/main/java/calculator/Calculator.java
> +        Scanner scanner = new Scanner(System.in);
그렇네요 이렇게 짜면 수정한것이 의미가 없어지네요!! 감사합니다

2020-02-10 03:03 UTC, include42 commented on src/main/java/calculator/Calculator.java
> +            start();
감사합니다!! 구조 때문에 고민을 많이 했는데 그게 더 좋은 것 같습니댜

2020-02-10 03:25 UTC, include42 commented on src/main/java/calculator/Calculator.java
> +        return scanner.nextLine().trim();
이런 부분을 의식하지 못하고 많이 놓치게되네요!! 말씀 듣고 나니 고쳐야겠다 싶습니다. 감사합니다!!

2020-02-10 03:25 UTC, include42 commented on src/main/java/calculator/OperatorType.java
> +interface OperationMethod {
감사합니다!! 읽어보면서 왜 그렇게 해야하는지도 고민 많이 할 수 있었습니다!!

2020-02-10 03:26 UTC, include42 commented on src/main/java/calculator/OperatorType.java
> +    public static OperatorType findApplyToOperator(String inputOperator) throws IllegalArgumentException {
이름을 어떻게 지어야 할 지 고민했는데, 말씀듣고나니 방향이 잡히네요 감사합니다ㅎㅎ

2020-02-10 03:26 UTC, include42 commented on src/main/java/calculator/OperatorType.java
> +            if (calculatorType.toString().equals(inputOperator)) {
stream이 있었네요!! 수정해 봐야겠습니다!!!!