[라테] 온보드 - 학습 테스트, 단위 테스트입니다.
woowacourse/java-calculator pull request #26
Opened 2020-02-07 08:44 UTC by minuyim

첫 리뷰요청 보내드립니다. 감사합니다!

2020-02-08 03:02 UTC, jaeyeonling requested changes
안녕하세요. 리뷰를 맡은 재연링입니다!
요구사항에 맞게 잘 구현해주셨어요. 👍 
몇 가지 코멘트 남겼으니 확인하시고 궁금하신 점 있으면 DM 주세요 :)

2020-02-08 03:02 UTC, jaeyeonling commented on src/main/java/domain/Operator.java
> +			.orElseThrow(() -> new IllegalArgumentException());
해당 문제에 대한 상세 메시지를 포함하지 않는 것과 추상화 레벨에 맞는 메시지를 포함하는 것은 어떠한 차이가 있을까요?

`이펙티브 자바 아이템 75. 예외의 상세 메시지에 실패 관련 정보를 담으라`를 참고하시면 좋습니다.

2020-02-08 03:02 UTC, jaeyeonling commented on src/main/java/domain/Calculator.java
> +		for (int i = 0; i < expressionAsArray.length; i+=2) {
```suggestion
		for (int i = 0; i < expressionAsArray.length; i += 2) {
```

자바 코딩 규칙을 위반하셨습니다!
https://myeonguni.tistory.com/1596 를 참고해주세요

2020-02-08 03:02 UTC, jaeyeonling commented on src/main/java/domain/Calculator.java
> +		} catch (Exception e) {
```suggestion
		} catch (NumberFormatException e) {
```

```
     * @exception  NumberFormatException if the {@code String}
     *             does not contain a parsable {@code int}.
```
`Integer.parseInt` 문서에 위와 같이 나와있는데요.
정확한 예외 상황에 대해 예외처리한다면 어떠한 차이가 있을지 고민해보아요.

2020-02-08 03:02 UTC, jaeyeonling commented on src/main/java/domain/Calculator.java
> +		if (expressionAsArray.length == 1) {
매직 넘버란 코드 안에 작성된 구체적인 숫자 혹은 문자열을 말합니다. 그리고 매직 넘버의 단점은 아래와 같습니다.

- 의미를 이해하기 어렵다.
- 복수의 장소에서 사용된다면 변경하기 힘들다.

그런 매직 넘버는 의미를 나타낼 수 있는 상수로 치환하여 코드의 가독성을 높여 보는 것은 어떨까요?

2020-02-08 03:02 UTC, jaeyeonling commented on src/main/java/domain/Calculator.java
> +			if (isOperator(expressionArg)) {
```suggestion
			if (Operator.isOperatorSymbol(expressionArg)) {
```

`Operator.isOperatorSymbol`로 바로 바이패스 하는 메서드를 분리한다면 어떠한 차이가 있을지 고민해보아요.

2020-02-08 03:02 UTC, jaeyeonling commented on src/main/java/domain/Operator.java
> +public enum Operator {
열거형 분리 👍

2020-02-09 01:55 UTC, minuyim commented on src/main/java/domain/Calculator.java
> +		for (int i = 0; i < expressionAsArray.length; i+=2) {
이 부분을 놓쳤군요! 수정했습니다.

2020-02-09 01:58 UTC, minuyim commented on src/main/java/domain/Calculator.java
> +		} catch (Exception e) {
이 부분은 숫자 변환이 불가능한 부분을 예외 처리로 잡아야 하는 부분이니 모든 Exception을 처리하는 것보다 NumberFormatException을 통해 예외 처리를 해 예측하지 못한 예외를 잡는 부분을 제거하겠습니다.

2020-02-09 02:00 UTC, minuyim commented on src/main/java/domain/Calculator.java
> +		if (expressionAsArray.length == 1) {
저도 다시 보니 왜 이 부분이 필요한 지 바로 이해하기 어렵다는 느낌을 받는 부분이었습니다. 이러한 부분을 상수 처리하여 보다 가독성을 높일 수 있다면 좋겠다는 생각을 하게 되었습니다. 다만 이 부분은 불필요한 if문인것 같아 삭제처리 하였습니다.

2020-02-09 02:03 UTC, minuyim commented on src/main/java/domain/Operator.java
> +			.orElseThrow(() -> new IllegalArgumentException());
이 부분의 예외는 isOperator를 통해 현재에는 예외가 발생하기 힘든 부분이라 생각하여 처음에는 메세지를 작성하지 않았습니다. 리뷰해주신 점을 생각해보니 추후에 구조를 수정하여 문제가 발생시 어떤 오류인지 찾기 힘들 수 있다는 점을 알게 되었습니다. 리뷰 참고하여 메세지를 추가하였습니다.

2020-02-09 02:08 UTC, minuyim commented on src/main/java/domain/Calculator.java
> +			if (isOperator(expressionArg)) {
혹시 바이패스하는 메서드를 분리한다는 것이 Operator에서 만들어놓은 static 메소드를 바로 이용해야 한다는 뜻일까요?

2020-02-09 02:08 UTC, minuyim commented on src/main/java/domain/Operator.java
> +public enum Operator {
감사합니다!

2020-02-09 04:53 UTC, jaeyeonling commented on src/main/java/domain/Calculator.java
> +			if (isOperator(expressionArg)) {
`isOperator` 메서드를 보면 바로 `Operator.isOperatorSymbol`를 호출하고 있습니다. (이를 바이패스한다고 합니다.)
그렇다면 `isOperator` 메서드로 분리 하였을 때 어떠한 차이점이 있을지 궁금하여 질문 남겼습니다!

2020-02-09 12:15 UTC, jaeyeonling approved these changes
코멘트 반영 잘 해주셨어요 👍 
해당 요청은 머지하도록 하겠습니다. 
고생하셨습니다 :)

2020-02-09 12:15 UTC, merged