[하비] 온보딩 미션 제출합니다.
woowacourse/java-calculator pull request #29
Opened 2020-02-07 08:47 UTC by hyochan-Kim

잘 부탁드립니다.
감사합니다.

2020-02-07 23:34 UTC, young891221 requested changes
안녕하세요, 이번에 리뷰를 맡게 된 하비라고 합니다:)
요구사항 기반하여 잘 구현해 주셨네요 👍 
몇 가지 코멘트 남겼습니다. 잘 부탁드립니다ㅎㅎ

2020-02-07 23:34 UTC, young891221 commented on src/main/java/calculator/Input.java
> +            return inputString();
에러 발생시 메시지만 출력하고 계속 진행이 되는 로직으로 보여집니다.
에러가 발생하면 메시지 출력 & throw exception으로 처리하여 어플리케이션이 종료되는게 더 좋지 않을까요??ㅎ

2020-02-07 23:34 UTC, young891221 commented on src/main/java/calculator/Validator.java
> +        operators.add("/");
고정적인 오퍼레이터들에 대해 `enum`으로 관리하면 어떠한 장점이 있을까요?ㅎ

2020-02-09 13:13 UTC, hyochan-Kim commented on src/main/java/calculator/Validator.java
> +        operators.add("/");
enum으로 관리하면 향후 추가/변경시에 전체 코드를 바꾸지 않아도 될 것 같습니다:)

2020-02-09 13:16 UTC, hyochan-Kim commented on src/main/java/calculator/Input.java
> +            return inputString();
해당 부분은 유효하지 않은 입력이 들어 왔을 경우,
에러를 잡아서 메세지 출력 후, 다시 입력을 받도록 하는 것이였습니다.
유효하지 않은 입력이 계속 들어올 시, 메모리에 문제가 될 것 같네요.
전체 구조 수정하면서, 어플리케이션이 종료되게끔 변경 하였습니다.
더 좋은 방법을 고민해보겠습니다.
감사합니다.

2020-02-10 13:14 UTC, young891221 approved these changes
리뷰 반영 잘 해주셨네요 💯 
고생하셨습니다. 머지할게요~!

2020-02-10 13:15 UTC, merged