[범블비] 온보딩 미션 제출합니다.
woowacourse/java-calculator pull request #35
Opened 2020-02-07 08:50 UTC by ddaaac

안녕하세요. 범블비입니다.
리뷰 부탁드립니다!
감사합니다.

2020-02-08 02:19 UTC, jaeyeonling requested changes
안녕하세요. 리뷰를 맡은 재연링입니다!
요구사항에 맞게 구현해 주셨네요 👍
몇 가지 코멘트 남겼으니 확인하시고 궁금하신 점 있으면 DM 주세요 :)

2020-02-08 02:19 UTC, jaeyeonling commented on src/main/java/calculator/CalculatorType.java
> +                .orElseThrow(Exception::new);
해당 문제에 대한 상세 메시지를 포함하지 않는 것과 추상화 레벨에 맞는 메시지를 포함하는 것은 어떠한 차이가 있을까요?
추가적으로 `Exception과 RuntimeExeption은 어떠한 차이가 있을까?` 에 대해서도 고민해보면 좋을 것 같아요.

`이펙티브 자바 아이템 75. 예외의 상세 메시지에 실패 관련 정보를 담으라`를 참고하시면 좋습니다.

2020-02-08 02:19 UTC, jaeyeonling commented on src/main/java/calculator/Main.java
> +                source.printResult(source.calculateInputs());
입/출력과 도메인 로직을 분리한다면 어떠한 차이가 있을지 고민해보아요.

2020-02-08 02:19 UTC, jaeyeonling commented on src/main/java/calculator/Main.java
> +            }
모든 Exception을 묶어서 처리하면 개발하는 것은 편하지만, 사용자는 정확한 에러를 파악하기 힘들어져요.
친화적인 에러 메시지를 만들기 위해 어떠한 방법이 있을지 고민해보아요.

2020-02-08 02:19 UTC, jaeyeonling commented on src/main/java/calculator/Source.java
> +    }
테스트 코드에서 검증을 위해 만든 것으로 보입니다.
이러한 방법은 개발자에게 의문을 줄 수 있고, 해당 생성자로 만들어진 객체는 제 역할을 하지 못하는데요. 

- 검증하는 역할만 담당하는 클래스로 분리한다.
- 검증 메서드를 static 으로 변경한다.

등 다른 방법이 어떤게 있을지 고민해보고 어떠한 차이가 있는지 고민해보아요.

2020-02-08 02:19 UTC, jaeyeonling commented on src/test/java/calculator/CaculatorTypeTest.java
> +public class CaculatorTypeTest {
해당 기능에 대한 테스트가 있으면 좋을 것 같아요!

2020-02-08 12:13 UTC, ddaaac commented on src/main/java/calculator/CalculatorType.java
> +                .orElseThrow(Exception::new);
메서드에 throws Excpetion을 붙여야하는 이유에 대해 궁금했었는데 한번에 이해됐습니다. 감사합니다.

이 때, 표준 예외를 사용할지 커스텀 예외를 사용할지 고민이 됩니다.
커스텀 예외를 만들어 InvalidOperatorException 등의 커스텀 예외를 만든다면 사용자 입장에서 더 명확하게 그 의미를 알 수 있을 것 같고,

`이펙티브 자바 아이템 60. 표준 예외를 사용하라`에 따르면 표준 예외인 IllegalArgumentException을 사용하는게 좋을 것 같습니다. 어느 쪽을 따라야할지 모르겠습니다.

2020-02-08 12:14 UTC, ddaaac commented on src/main/java/calculator/Main.java
> +                source.printResult(source.calculateInputs());
입/출력에 관한 로직을 StringHandler로 모두 옮겼는데 올바르게 분리했는지 모르겠습니다.

2020-02-08 12:14 UTC, ddaaac commented on src/main/java/calculator/Main.java
> +            }
현재 제가 의도한 예외는 모두 IllegalArgumentException을 따르고 있어서 이 경우만 처리할 수 있게 바꿨습니다. 사용자가 어떤 에러인지 알기 쉽게 하는 작업이 쉬운 작업이 아니네요... 이 부분에 부족한 점이 있으면 말씀해주시면 정말 감사하겠습니다.

이와 별개로 질문이 몇가지 있습니다.
1. 현재 try ~ catch ~ 를 main 함수에서 사용해서 예외를 잡아내고 있는데 이런 방식이 올바른 방법인지 모르겠습니다. 
1. 예외처리의 범위가 궁금합니다.

    예를 들어, 제가 수정한 코드에서 제가 의도한 예외처리는 Main.java의 `Formula formula = new Formula(inputs)`에서 발생합니다.
    
    위 코드에서 예외가 발생하지 않았다면 `formula`는 올바른 식을 갖게 되므로 `formula.calculateFormula()` 메서드는 올바르게 작동할 것이라고 예측할 수 있습니다.
    
    이 때, try catch 구문을  `Formula formula = new Formula(inputs)`에만 적용시켜주면 되는지, `formula.calculateFormula()`에도 적용해야하는지 궁금합니다.(개발자가 의도한 예외처리만 try catch로 잡아내면 되는지, 의도하지 않은 예외를 잡기 위해서도 try catch를 사용해야하는지 궁금합니다)

2020-02-08 12:14 UTC, ddaaac commented on src/main/java/calculator/Source.java
> +    }
검증을 위한 별도의 생성자가 필요없게 테스트 코드를 수정하여서 해결했습니다.

이렇게 수정한 것과 별개로 말씀해주신 부분에 대해 생각해봤는데
- 검증을 담당하는 클래스를 따로 만들 경우, 나중에 코드가 수정될 경우 따로 만든 클래스의 코드 또한 수정해야하는 상황이 발생할 것 같습니다.
- 검증 메서드를 static으로 변경하는 경우, 의도치 않은 에러가 발생할 수 있을 것 같고, 검증을 위해 메서드의 속성을 바꾸는 것은 주객을 바꿔버리는 일인 것 같습니다.

따라서, 주어진 코드 안에서 테스트를 할 수 있게 테스트 코드를 짜는게 맞는 것 같습니다.(혹시 다른 좋은 방법이 있다면 알려주시면 감사하겠습니다...!)

2020-02-08 12:14 UTC, ddaaac commented on src/test/java/calculator/CaculatorTypeTest.java
> +public class CaculatorTypeTest {
Formula에 계산을 테스트하는 부분을 추가하였고, 이 부분에 포함되는 테스트라고 생각하여 삭제했습니다.

이렇게 상위 - 하위의 포함 관계에 있는 메서드들은 테스트할 때, 상위 메서드를 테스트해야하는지 하위 메서드 여러개를 테스트 해야하는지 궁금합니다.

2020-02-09 04:12 UTC, jaeyeonling commented on src/main/java/calculator/CalculatorType.java
> +                .orElseThrow(Exception::new);
일단 저는 커스텀 예외로 만들어 처리하는 것을 선호합니다.
그 이유는 현업에서 스프링과 같은 프레임 워크를 사용한다면 예외처리를 공통적으로 처리하게 되는데 Exception에 응답 정보(Body, Header) 등을 포함하기 때문인 것 같네요. ㅎㅎ

프로젝트를 하게 된다면 프로젝트의 규칙을 따르겠지만.. 
지금은 미션을 진행하며 두 방법을 사용해보고 어떤 방법이 차이점이 있는지 직접 확인 해본다면 더욱 체감하실 수 있을 것 같습니다.
미션은 굉장히 많으니 매번 많은 실험을 하시는 것도 실력 향상에 도움이 많이 되실거에요!

2020-02-09 04:15 UTC, jaeyeonling commented on src/main/java/calculator/Main.java
> +                source.printResult(source.calculateInputs());
대부분 InputView, OutputView와 같은 클래스로 분리하는 편 입니다.
StringHandler라는 네이밍보다 위의 네이밍이 의미를 더욱 내포하고 있는 것 같네요.

2020-02-09 04:27 UTC, jaeyeonling commented on src/main/java/calculator/Main.java
> +            }
어떠한 입력 값을 받았는지 까지 포함하여 잘 처리해주셨어요 👍 
OperatorType의 경우 어떠한 값만 허용한다. 등을 포함하는 방법도 있을 것 같습니다!

1. 현재 try ~ catch ~ 를 main 함수에서 사용해서 예외를 잡아내고 있는데 이런 방식이 올바른 방법인지 모르겠습니다.

의도가 값을 잘못 입력한다면 계속해서 입력을 받는다. 라면 위와 같이 처리하는 것은 나쁘지 않습니다.
하지만 위와 같은 상황에서 프로그램을 종료할 수 있는 방법이 없기 때문에 
* 잘못된 값을 입력할 경우 에러 메시지를 나타내며 프로그램을 종료한다. 
* 'q'라는 값을 입력하면 종료한다.

와 같은 방법도 좋을 것 같네요!

추가적으로 나중에 스프링과 같은 프레임워크를 사용하게 된다면 인프라 로직은 AOP와 같은 방식으로 별도 처리하게 되실거에요.
(로깅, 예외처리, 트랜잭션 등을 인프라 로직이라 부릅니다.)

2. 예외처리의 범위가 궁금합니다.

해당 범위는 기획에 따라 달라지는 내용일 것 같은데요.
어떠한 상황을 의도하였는지 생각해보면 좋을 것 같아요.

2020-02-09 04:35 UTC, jaeyeonling commented on src/main/java/calculator/Source.java
> +    }
* 검증을 담당하는 클래스를 따로 만들 경우, 나중에 코드가 수정될 경우 따로 만든 클래스의 코드 또한 수정해야하는 상황이 발생할 것 같습니다.

검증하는 역할을 별도의 클래스로 분리하는 것을 의미하는데요.
예를 들어 해당 클래스를 생성하는 것의 조건이 어렵다면 팩토리로 사용하여 생성의 역할을 분리할 수 있습니다.
코드가 수정될 경우 만든 클래스를 수정하는 것은 
생성의 기능이 변경됬다. = 팩터리 수정
계산에 대한 로직이 변경됐다. = 계산 관련 수정
으로 될 수 있겠네요.

* 검증 메서드를 static으로 변경하는 경우, 의도치 않은 에러가 발생할 수 있을 것 같고, 검증을 위해 메서드의 속성을 바꾸는 것은 주객을 바꿔버리는 일인 것 같습니다.

의도치 않은 에러가 발생하는 경우가 어떤게 있을까요?

말씀하신대로 주어진 코드 안에서 테스트할 수 있게 구현하는 것이 가장 좋은 방법일 것 같네요 👍

2020-02-09 04:38 UTC, jaeyeonling commented on src/test/java/calculator/CaculatorTypeTest.java
> +public class CaculatorTypeTest {
나중에 TDD로 개발하게 되면 많이 겪는 문제인데요.
개발 과정에서 클래스로 분리되어 자연스럽게 테스트 코드가 분리된 클래스의 테스트로 이동하게 됩니다.
테스트를 한다는 개념에서는 하위 포함 관계에서 검증을 했기 때문에 추가적으로 검증할 필요는 없습니다.
하지만 테스트 코드의 기능 중 `해당 클래스를 사용하는 클라이언트에게 사용법을 알려준다.`라는 것도 있는데요.
이러한 관점에서 봤을 때는 하위에서 검증하는 부분도 상위에 있는 것이 좋겠네요!

2020-02-09 04:49 UTC, jaeyeonling requested changes
전체적인 로직에 많은 변화가 생겼네요!
남겨주신 코멘드에 답변과 함께 몇 가지 코멘트 확인해주세요.

2020-02-09 04:49 UTC, jaeyeonling commented on src/main/java/calculator/Formula.java
> +    }
해당 캐스팅을 추가하여 얻을 수 있는 장점이 어떤 것이 있을까요?
상속 관계는 어떠한 상황에 사용하는지 고민해보면 좋을 것 같아요.

2020-02-09 04:49 UTC, jaeyeonling commented on src/main/java/calculator/Formula.java
> +        return !isOddNumber(formula.size());
```suggestion
        return isEvenNumber(formula.size());
```

!와 같은 부정문은 가독성을 해칠 수 있어요.

2020-02-09 04:49 UTC, jaeyeonling commented on src/main/java/calculator/Operand.java
> +        operand = Double.parseDouble(input);
```suggestion
        this(Double.parseDouble(input));
```

생성자가 여러 개라면 생성 시 로직이 변경됐을 때 모든 생성자를 변경해야하는 일이 발생할 수 있어요.
최종적인 초기화는 하나의 생성자에서 처리해주세요!

2020-02-09 04:49 UTC, jaeyeonling commented on src/main/java/calculator/OperatorType.java
> +    public static OperatorType validateOperator(String input) {
```suggestion
    public static OperatorType of(String operator) {
```

`validateOperator` 라는 네이밍은 검증의 의미를 포함하는 것으로 보일 수 있어요.
팩토리 메서드의 역할을 하고 있다는 것을 이름으로 나타내 보는 것이 어떨까요?

2020-02-09 09:42 UTC, ddaaac commented on src/main/java/calculator/Formula.java
> +    }
캐스팅 외에 다른 방법을 몰라서 캐스팅을 사용했는데, 지적해주신 부분을 공부하다보니 Wrapper를 사용하는 방법이 있어서 나름 흉내내봤습니다. 올바르게 사용했는지 모르겠습니다.

또, 이 부분에서 일급 컬렉션인 Formula의 필드인 formula가 처음 생성된 이후 변경되지 않게 하기 위해서 Queue에서 List로 변경하고, 다음 index를 찾아가는 부분을 index++ 로 바꿨습니다. 이 부분이 별로인 것 같은데 현업에서 이런 식의 코딩은 피하는지 궁금합니다. 그리고 이 방식이 좋지 않다면, 커스텀 Queue를 만들어 formula를 관리하는 것은 어떻게 생각하시는지 궁금합니다.

2020-02-09 10:45 UTC, ddaaac commented on src/main/java/calculator/Operand.java
> +        operand = Double.parseDouble(input);
이 부분에 하나 더 여쭤보고 싶은게 있습니다.

`Double.parseDouble()`은 NumberFormatException 을 throw하는데, 만약 이 예외처리로는 설명이 불충분하다고 느끼면 이 부분을 try~ catch~ 구문을 사용해서 커스텀 예외를 발생시키는 것도 하나의 방법이 되는지 궁금합니다!

2020-02-09 13:20 UTC, jaeyeonling commented on src/main/java/calculator/Operand.java
> +        operand = Double.parseDouble(input);
네! 말씀하신 상황에서 커스텀 예외를 발생하는 것은 좋은 방법입니다. 👍

2020-02-09 13:32 UTC, jaeyeonling commented on src/main/java/calculator/Formula.java
> +    private static final int FIRST_ELEMENT = 0;
클래스 구현 순서 
class A {
    상수(static final) 또는 클래스 변수
    인스턴스 변수
    생성자
    메소드
}

에 맞게 수정해주세요!

2020-02-09 13:32 UTC, jaeyeonling commented on src/main/java/calculator/Formula.java
> +    }
계산에 필요한 값을 관리하는 클래스를 만드는 것은 좋다고 생각합니다!
List로 가지고 있기 위해 FormulaElement를 상속받아 구현하는 것은 좋지 않은 설계로 보여집니다.

클래스 중심적인 사고가 아닌 객체 중심적인 사고를 하면 좋은 설계를 할 수 있는데요.

* 어떠한 책임을 가지고 어떠한 역할을 하는지 생각한다.
* 상태의 관점이 책임과 협력 관점에서 본다.

를 생각하며 설계해보세요!

2020-02-09 13:39 UTC, jaeyeonling requested changes
질문주신 코멘트에 참고하셔서 반영해주세요!
궁금하신 점 있으시면 언제든지 DM 주세요. :)

2020-02-09 13:39 UTC, jaeyeonling commented on src/main/java/calculator/Formula.java
> +class FormulaElement {
해당 클래스를 Formula.java에 같이 둔 이유는 어떤게 있을까요?

2020-02-09 13:39 UTC, jaeyeonling commented on src/main/java/calculator/Formula.java
> +    private List<FormulaElement> formula;
https://github.com/woowacourse/java-calculator/pull/35#discussion_r376784254 해당 코멘트를 확인해주세요!

2020-02-10 15:02 UTC, jaeyeonling approved these changes
코멘트를 잘 반영해주셔서 코드가 굉장히 깔끔하네요 💯 
해당 요청은 머지하도록 하겠습니다. 
고생하셨습니다 :)

2020-02-10 15:02 UTC, jaeyeonling commented on src/main/java/calculator/Calculator.java
> +        while(formula.size() > ZERO_SIZE) {
```suggestion
        while (formula.size() > ZERO_SIZE) {
```

인텔리제이의 오토 포멧팅을 사용하는 습관을 들이는 연습을 해보세요!

The auto-formatting shortcut in IntelliJ
* For windows Ctrl + Alt + L.
* For ubuntu Ctrl + Alt + windows + L.
* For Mac Command + Option + L.

2020-02-10 15:02 UTC, jaeyeonling commented on src/main/java/exceptions/InvalidOperatorException.java
> +        super(String.format(invalidOperator + " is not valid operator\nOnly +, -, *, / is permitted"));
```suggestion
        super(invalidOperator + " is not valid operator\nOnly +, -, *, / is permitted");
```
```suggestion
        super(String.format("'%s' is not valid operator\nOnly +, -, *, / is permitted", invalidOperator));
```

친절한 에러 메시지 👍 
하지만 `String.format`이 제 기능을 못하고 있어요.

2020-02-10 15:02 UTC, merged