[또링] 온보딩 코드리뷰 요청합니다.
woowacourse/java-calculator pull request #37
Opened 2020-02-07 08:51 UTC by jnsorn

리뷰 요청드립니다. 감사합니다.. 부족한 부분이 많은데 많이 리뷰해주시면 열심히 고쳐보겠습니다!..😊

2020-02-08 01:20 UTC, hongsii requested changes
안녕하세요, 또링~ 이번에 리뷰를 맡게 된 홍시입니다.
요구사항에 맞게 잘 구현해주셨네요! 👍 
몇 가지 피드백드렸으니, 확인하셔서 반영해주세요 :)

2020-02-08 01:20 UTC, hongsii commented on src/main/java/model/StringValue.java
> +public class StringValue {
`StringValue` 라는 이름은 현재 이 객체를 표현하기에 모호한 이름인 듯 합니다. 좀 더 클래스의 내용이 드러날 수 있는 이름으로 바꿔보면 어떨까요?

2020-02-08 01:20 UTC, hongsii commented on src/main/java/model/StringValue.java
> +    private List<String> operatorList = new ArrayList<>();
보통 컬렉션 타입의 변수를 선언할 때는 변수명에 타입을 넣기 보다 좀 더 자연스럽게 읽히는 복수형으로 네이밍을 합니다.
* `numberList` -> `numbers`

2020-02-08 01:20 UTC, hongsii commented on src/main/java/validator/InputValidator.java
> +    public boolean isCorrectEvanIndex(List<String> evenArr) {
메서드마다 역할을 부여해서 잘 분리하셨습니다 👍 
다만, 저는 이  메서드의 이름만 보고 "배열 안의 짝수 인덱스를 체크하는건가?" 라는 생각이 들었습니다.
짝수라는 의미는 이 메서드를 호출하는 쪽에서 알아야할 내용이며, 현재 이 메서드는 짝수와 상관없이 "배열 안의 모든 요소가 숫자가 맞는지 확인"하는 일을 하고 있습니다. 이러한 역할이 드러나는 이름으로 바꿔보면 어떨까요?

2020-02-08 01:20 UTC, hongsii commented on src/main/java/validator/InputValidator.java
> +            if (inputArr[i].equals("0") && inputArr[i - 1].equals("/")) {
상수랑 객체 비교 시 객체가 null이면 NPE(NullPointerException)가 날 수 있어서 보통 상수를 앞에 배치합니다.

``` java
"0".equals(inputArr[i])
```

2020-02-08 01:20 UTC, hongsii commented on src/main/java/validator/InputValidator.java
> +            if (!Arrays.asList(signs).contains(operator)) {
매번 `Array` 를 `List` 로 바꾸기 보다 미리 `List` 로 선언해도 좋을 것 같아요!

2020-02-08 01:20 UTC, hongsii commented on src/main/java/controller/Controller.java
> +        } while (!stringInput.isValidator());
유효하지 않은 `StringValue` 의 인스턴스가 불필요하게 생성될 필요가 있을까요?
`StringValue` 인스턴스가 생성되기 전 `InputValidator` 를 통해 유효한 입력값인지 검증하도록 바꿔보면 어떨까요?

2020-02-08 01:20 UTC, hongsii commented on src/main/java/validator/InputValidator.java
> +        return true;
분기문을 아래와 같이 바꾸면 좀 더 가독성이 좋아질 듯 합니다 :)

``` java
return isCorrectEvanIndex(evenArr) && isCorrectOddIndex(oddArr)
```

2020-02-08 01:20 UTC, hongsii commented on src/main/java/controller/Controller.java
> +    private final String DIV = "/";
자바에서는 이러한 상수를 묶어서 관리할 수 있는 방법이 무엇이 있을까요?

2020-02-08 01:20 UTC, hongsii commented on src/main/java/controller/Controller.java
> +            }
클래스를 인터페이스로 변경하고 아래와 같은 인터페이스를 구현하도록 바꿔보면 어떨까요?
그리고 이 구현체를 어떻게 연산자 기호와 연관 지을 수 있을 지 고민해서 분기문을 제거해보시면 좋을 듯 합니다 :)

``` java
public interface Calculator {
    int calculate(int number1, int number2);
}
```

2020-02-08 01:20 UTC, hongsii commented on src/test/java/study/SetTest.java
> +    @CsvSource(value = {"1:true", "2:true", "3:true", "4:false"}, delimiter = ':')
Junit 활용 👍

2020-02-08 01:20 UTC, hongsii commented on src/main/java/validator/InputValidator.java
> +    private final int ODD = 1;
상수는 `static` 키워드를 통해 메모리에 한 번만 할당하도록 선언하는 게 좋습니다.

* [참고](https://djkeh.github.io/articles/Why-should-final-member-variables-be-conventionally-static-in-Java-kor/)

2020-02-09 07:38 UTC, jnsorn commented on src/main/java/model/StringValue.java
> +public class StringValue {
StringValue도 나름(..) 고민하여 나온 이름인데, 제가 봐도 너무 모호한 이름인 것 같습니다. 객체의 특성을 살릴 수 있는 단어를 이용해서 네이밍을 해야겠네요. 감사합니다. 😅

2020-02-09 07:39 UTC, jnsorn commented on src/main/java/model/StringValue.java
> +    private List<String> operatorList = new ArrayList<>();
항상 추천 이름으로 ~list와 ~s가 나와서 고민했는데, 아무래도 타입을 안넣은 변수명이 더 용이할 것 같네요! 감사합니다 ☺

2020-02-09 07:43 UTC, jnsorn commented on src/main/java/validator/InputValidator.java
> +    public boolean isCorrectEvanIndex(List<String> evenArr) {
저에게 특히 어려운 것 중 하나가 네이밍인데, 하나 하나 자세한 리뷰 감사합니다! 처음 구현할 때에는 매개변수로 _짝수 index array_가 아닌 _전체 array_를 받아서 검사를 진행했습니다. 그래서 처음 네이밍을 짝,홀수 의미가 포함되도록 네이밍 한 것 같습니다. 함수가 하는 일이 무엇인지 명확하게 드러나도록 수정하였습니다! 😊

2020-02-09 07:48 UTC, jnsorn commented on src/main/java/validator/InputValidator.java
> +            if (!Arrays.asList(signs).contains(operator)) {
네 감사합니다 🙂

2020-02-09 07:49 UTC, jnsorn commented on src/main/java/validator/InputValidator.java
> +        return true;
코드를 꼼꼼히 확인하지 못한 것 같습니다 ㅎㅎ😅 수정하였습니다!

2020-02-09 07:49 UTC, jnsorn commented on src/main/java/controller/Controller.java
> +        } while (!stringInput.isValidator());
좋은 지적 감사합니다! 유효한 입력 값만 객체가 생성되도록 코드 수정하였습니다!

2020-02-09 07:50 UTC, jnsorn commented on src/main/java/validator/InputValidator.java
> +    private final int ODD = 1;
감사합니다. 수정하였습니다!

2020-02-09 07:56 UTC, jnsorn commented on src/main/java/controller/Controller.java
> +            }
인터페이스를 이용해서 코드를 수정해보다가 아무래도 연산자와 연산자의 행위가 더 연관이 있으면 좋겠다 생각을 해서 enum을 이용하여 고쳐보았습니다. 많이 사용해보지않아서 이런식으로 짜는것이 맞나에 대한 확신이 부족합니다..!! 😥

2020-02-09 07:57 UTC, jnsorn commented on src/main/java/validator/InputValidator.java
> +            if (inputArr[i].equals("0") && inputArr[i - 1].equals("/")) {
생각도 못했던 부분입니다. 감사합니다!

2020-02-10 02:35 UTC, hongsii approved these changes
피드백 반영을 잘 해주셨네요! 💯
사소한 피드백 몇가지 드렸으니, 참고해주세요!
이번 단계는 여기서 머지하겠습니다 :)

2020-02-10 02:35 UTC, hongsii commented on src/main/java/model/OperatorType.java
> +    final private String operator;
보통 인스턴스 변수는 접근제어자 -> final 순으로 선언합니다~

2020-02-10 02:35 UTC, hongsii commented on src/main/java/model/OperatorType.java
> +public enum OperatorType {
Enum 활용 💯

2020-02-10 02:35 UTC, hongsii commented on src/main/java/calculator/Calculator.java
> +        }
`toString()` 은 객체를 사람이 읽기 쉽게 하기 위한 용도로 설계되었습니다. 그래서 로직 용도로는 적절하지 않다고 생각합니다.
클래스 외부에서 기호를 사용해야 한다면 getter를 사용하는 게 더 적절하다고 생각합니다.

현재 `String` 으로 `OperatorType` 을 찾는 로직이 여러 군데에 존재합니다.
`OperatorType` 클래스의 클래스 메서드(static)로 `String` 기호를 인자로 전달하면 일치하는 기호의 `OperatorType` 을 반환하는 메서드를 만들어서 여러 군데에서 사용하도록 바꿔도 좋을 것 같습니다.

* [javadoc - Object#toString()](https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#toString--)

2020-02-10 02:36 UTC, merged

2020-02-13 07:50 UTC, jnsorn commented on src/main/java/calculator/Calculator.java
> +        }
네 감사합니다 해당 피드백을 참고하여 수정 및 메서드 추출하였습니다. 😀