[타미] 온보딩
woowacourse/java-calculator pull request #7
Opened 2020-02-07 08:08 UTC by moonyoungCHAE

코드 리뷰 신청합니다. :)
감사합니다.

2020-02-08 06:52 UTC, Hue9010 requested changes
안녕하세요. 이번 리뷰를 맡은 휴라고 합니다 :)
전체적인 로직은 깔끔하게 잘 구현해 주셨습니다.  👍 
다만 InputValues의 static 사용은 고민해 볼 지점인 것 같네요. 몇가지 피드백 남겼습니다.
잘 부탁드립니다~!

2020-02-08 06:52 UTC, Hue9010 commented on src/main/java/InputValues.java
> +                throw new IllegalArgumentException("피연산자가 잘못되었습니다.");
발생한 예외에 대한 상세한 메시지 👍

가능하면 catch 절에다가는 모든 예외를 다 catch하는 `Exception`보다는 현재 발생할 것으로 판단되는 예외를 넣어주는게 좋습니다.
Exception으로 catch시에는 예상하지 않은 예외가 발생하더라도 처리를 해 주기 때문에 나중에 28번 라인에서 피연산자가 잘못된게 아닌 다른 이유로 에러 발생 시 원인 파악이 어려울 수도 있고, 지금과 같이 catch 후 새로운 예외를 throw하는 경우가 아니라 다른 로직을 수행하는 경우라면 의도치 않은 결과가 나올수도 있습니다.

Double.parseDouble()의 상세 내용을 보시면 `NumberFormatException`을 발생시키는 걸 알 수 있습니다.
```
catch (NumberFormatException e) {
...
}
```

2020-02-08 06:52 UTC, Hue9010 commented on src/main/java/Operator.java
> +    abstract double operate(double num1, double num2);
java8 이상을 사용한다면 BiFunction을 사용해보시는건 어떨까요? 
https://www.slipp.net/questions/566

혹시나 말씀 드리면 BiFunction을 사용하는게 정답이란건 아닙니다. 다만, 변경이 아직 안어려운 상황이라면 사용해보지 않은 자바8 기능에 익숙해지는 것도 좋은 경험이라고 생각되네요. 정확히는 BiFunction보다는 람다에 익숙해져 보시는 걸 추천드립니다. :)

2020-02-08 06:52 UTC, Hue9010 commented on src/test/java/CalculatorTest.java
> +public class CalculatorTest {
다양한 테스트 케이스 작성  👍 
올바른 숫자, 올바른 연산자, 연산자로 수식이 끝나는 경우에 보면 성공/실패하는 케이스가 모두 섞여있는데 달리하여 성공하는 케이스와 실패하는 케이스로 작성해보면 어떨까요? (실패하는 케이스는 assertThatThrownBy로 의도한 exception이 발생했는지)

2020-02-08 06:52 UTC, Hue9010 commented on src/main/java/InputValues.java
> +        validateEndWithOperator();
생성시점에 validation 검증 👍 
아래 `public InputValues(String value)`도 마찬가지로 검증을 하는게 좋지 않을까요? 그렇다면 중복이 발생해 보이는데 어떻게 처리하면 좋을까요?

2020-02-08 06:52 UTC, Hue9010 commented on src/main/java/Main.java
> +        InputValues inputValues = new InputValues();
결국 이 부분이 가장 대표적인 static keyword 사용한 트릭으로 보이네요.
특히 ide에 의해서 아래 사진과 같이 생성 후 미사용하는 걸로 보이면 미사용 코드로 보고 지우게 될 수도 있습니다. 실제로도 제거를 해도 컴파일 상엔 문제가 없고요.

<img width="378" alt="스크린샷 2020-02-08 오후 3 29 11" src="https://user-images.githubusercontent.com/31364158/74080490-dacb0500-4a87-11ea-921e-a3f94a576fac.png">

2020-02-08 06:52 UTC, Hue9010 commented on src/main/java/Main.java
> +        InputValues inputValues = new InputValues();
https://vaert.tistory.com/101
static을 과도하게 혹은 잘못 사용된 코드가 보인다면 실제로 위 블로그에서 예시로 든 면접 상황이 이어지기도 합니다.

2020-02-08 06:52 UTC, Hue9010 commented on src/main/java/InputValues.java
> +    private static String[] values;
Calculator의 result같은 경우는 static 키워드가 없는 변수를 사용하셨는데 InputValues는 static 키워드를 사용하시고 이를 적극적으로 사용하신걸로 보이네요.
이로 인해서 여러가지 문제점이 보이는데 그 결과 중 하나가 CalculatorTest가 Calculator를 테스트 하지 않습니다.
또 Calculator는 InputValues가 생성된 다음만 정상적으로 실행 될 수 있습니다.

후자의 경우 Calculator가 계산을 하려면 InputValues가 필요하다는 맥락으로 해석할 수도 있는데 그렇다면 계산 할 때 InputValues를 파라미터로 전달 받아 사용하는 형태로 바꾸면 어떨까요?

그러면서 `InputValues`의 static 키워드를 모두 제거해보세요.

2020-02-10 01:35 UTC, closed without merging

2020-02-10 05:06 UTC, moonyoungCHAE reviewed
피드백 반영하면서 궁금한 점이 있었습니다. 😃

생성 시점에 validation하는 것이 좋다고 하셨는데,
그렇다면
생성자 () { 
 validation 함수1; // double 검증 함수, static 아님
 validation 함수2; // 연산자 검증 함수, static 아님
}
이런 식으로 코드를 작성한다면

Test Case에서
validation 함수1 기능을 검증하고 싶다면
validation 함수1만 call하는 게 아니라 생성자를 만들면서
validation 함수1, 2 모두 call하면서 진행하나요?

2020-02-10 05:06 UTC, moonyoungCHAE commented on src/main/java/Main.java
> +        InputValues inputValues = new InputValues();
Static에 대해 항상 찝찝한 기분이 있었는데 제가 딱 몰랐던 내용이네요! 감사합니다 😃