[Onboarding Mission] StringCalculator Ver1.0
woowacourse/java-calculator pull request #9
Opened 2020-02-07 08:12 UTC by yeonnseok

안녕하세요.
보스독입니다. 
온보딩 미션 : 문자열 계산기 리뷰 요청드립니다.
감사합니다. :)

2020-02-08 07:40 UTC, jeonghoon1107 commented on src/main/java/Controller/Operator.java
> +    public double compute(double result, int number) {
다른 기능들이 추가될 때마다 switch 문을 나열하는 것보다 더 좋은 방법이 있을 것 같아요 :)
switch문, if-else문을 사용하지 않고 코드를 작성해보면 좋을 것 같아요!

2020-02-08 07:54 UTC, jeonghoon1107 requested changes
안녕하세요 보스독!
몇 가지 피드백을 남겼으니 확인부탁드려요 :)

2020-02-08 07:54 UTC, jeonghoon1107 commented on src/main/java/Controller/Operator.java
> +        switch (this) {
다른 기능들이 추가될 때마다 switch 문을 나열하는 것보다 더 좋은 방법이 있을 것 같아요 :)
switch문, if-else문을 사용하지 않고 코드를 작성해보면 좋을 것 같아요!

2020-02-08 07:54 UTC, jeonghoon1107 commented on src/main/java/Controller/Operator.java
> +        for (Operator op : Operator.values()) {
매번 for문을 실행하는 것은 비효율적으로 보여요!

2020-02-08 07:54 UTC, jeonghoon1107 commented on src/test/java/study/SetTest.java
> +    @BeforeEach  // 각각의 테스트함수를 실행하기 직전에 매번 수행된다.
불필요한 주석은 삭제하는게 어떨까요?

2020-02-08 07:54 UTC, jeonghoon1107 commented on src/test/java/study/SetTest.java
> +     * 요구사항 1. set size 테스트
불필요한 주석보다 DisplayName을 사용해서 어떤 테스트를 하는지에 대해 명확하게 하면 좋을 것 같아요.

2020-02-08 07:54 UTC, jeonghoon1107 commented on src/main/java/Controller/Operator.java
> +        return null;
현재 정의하지 않은 Operator가 들어오면 어떻게 되나요?

2020-02-08 07:54 UTC, jeonghoon1107 commented on src/main/java/Controller/StringCalculator.java
> +        result = numbers.remove(0);
원본데이터를 훼손하는 것은 예기치 못한 오류를 일으킬 수 있을 것 같아요.
다른 방법으로 해결해보는 것이 좋을 것 같아요!

2020-02-08 08:14 UTC, jeonghoon1107 commented on src/test/java/StringCalculatorTest/StringCalculatorTest.java
> +    void calculate() {
더 다양한 케이스의 테스트가 있으면 좋을 것 같아요!
SetTest 클래스에서 사용한 것 처럼 ParameterizedTest를 사용해도 좋을 것 같아요

이곳에서도 배열의 첫번째 값을 제거하는 코드는 빠지면 좋을 것 같아요!

2020-02-09 15:39 UTC, yeonnseok commented on src/main/java/Controller/Operator.java
> +        switch (this) {
Enum 에 compute 메서드를 Override하는 형태로 수정했습니다.!

2020-02-09 15:56 UTC, yeonnseok commented on src/main/java/Controller/Operator.java
> +        for (Operator op : Operator.values()) {
Enum이 익숙하지 않아서 이 메서드를 도입할 때, String으로 Enum값을 가져오는 방법을 헤맸었는데,  애초에 연산자가 4개밖에 안되니 String과 Enum을 매칭해놓은 자료구조를 활용하는 방법으로 수정해보았습니다. :)

2020-02-09 15:58 UTC, yeonnseok commented on src/test/java/study/SetTest.java
> +    @BeforeEach  // 각각의 테스트함수를 실행하기 직전에 매번 수행된다.
하하.. 제가 처음알게된거라 메모용으로 적은 주석이 안지워졌군요
수정했습니다!

2020-02-09 16:10 UTC, yeonnseok commented on src/main/java/Controller/Operator.java
> +        return null;
정의하지 않은 Operator가 들어오면 null을 반환하고 null일 경우 예외처리를 발생하여 입력을 다시 받도록 했었습니다.

하지만 반복문을 통해 검사를 해야한다는 비효율 때문에 해당 코드를 삭제하고, HashMap 자료구조를 활용하는 쪽으로 수정하였습니다.

2020-02-09 16:10 UTC, yeonnseok commented on src/test/java/study/SetTest.java
> +     * 요구사항 1. set size 테스트
네! 되도록이면 주석을 다는 것보다는 메서드명이나, test코드에서는 Display name을 활용해보도록 하겠습니다.

2020-02-09 16:23 UTC, yeonnseok commented on src/main/java/Controller/StringCalculator.java
> +        result = numbers.remove(0);
우선 가장 가볍게 해결할 수있는 방법으로 remove를 get으로 변경해보았습니다.!
혹시 다른 좋은 방법이 있을까요?

> 리뷰어님! 추가적으로 궁금한 점이 있습니다. 
> 제가 지금 operators와 numbers로 리스트를 분리했는데, 이렇게 가공과정을 거쳐서 계산하는 게 좋은 건지
> 아니면, 예외처리를 통과한 입력값이니만큼 홀수번인덱스에는 연산자가, 짝수번째 인덱스에는 숫자가 들어있다고 가정하고, 
> 리스트를 나누지 않고, 반복문 한번만에 계산하는게 좋은 코드일까요?

2020-02-09 16:23 UTC, yeonnseok commented on src/test/java/StringCalculatorTest/StringCalculatorTest.java
> +    void calculate() {
네! 
더 많은 데이터를 한번에 테스트할 수 있는 코드를 추가해보도록하겠습니다 :)

2020-02-10 15:36 UTC, jeonghoon1107 approved these changes
안녕하세요 보스독!
피드백남겼으니 꼭 확인해주세요 :)
미션 진행하느라 고생많으셨습니다

2020-02-10 15:36 UTC, jeonghoon1107 commented on src/main/java/Controller/OperatorMap.java
> +public class OperatorMap {
따로 관리되어야하나요?

2020-02-10 15:36 UTC, jeonghoon1107 commented on src/test/java/StringCalculatorTest/InputValidationTest.java
> +        } catch (Exception e){
테스트 코드를 잘못 작성하셨네요!
예외 상황에 대한 테스트는 따로 작성하는게 좋아요.
https://www.baeldung.com/junit-assert-exception
참고해보시면 좋을 것 같아요.

2020-02-10 15:36 UTC, jeonghoon1107 commented on src/test/java/StringCalculatorTest/InputValidationTest.java
> +        } catch (Exception e){
위에 피드백을 참고해주세요!

2020-02-10 15:36 UTC, jeonghoon1107 commented on src/test/java/StringCalculatorTest/InputValidationTest.java
> +    void validateFirstAndLast(String sourceData, boolean answer) {
현재 코드에서 고려되어있지 않은 것 같은데 divide by zero 예외 상황도 함께 테스트하면 좋을 것 같아요!

2020-02-10 15:36 UTC, jeonghoon1107 commented on src/main/java/Controller/StringCalculator.java
> +            } catch (Exception e) {
일단 전부 변환해보고 예외가 발생하면 연산자로 보는 것은 좋지 않아요.
실제 예외가 발생했을 때를 함께 고려하면 좋을 것 같아요.

2020-02-10 15:36 UTC, merged

2020-02-11 05:09 UTC, yeonnseok commented on src/main/java/Controller/OperatorMap.java
> +public class OperatorMap {
따로 관리되는게 더 안좋은 코드 인건가요?
독립적인 자료형은 분리하는게 좋을 것같아서 분리했습니다.!

2020-02-11 05:12 UTC, yeonnseok commented on src/test/java/StringCalculatorTest/InputValidationTest.java
> +        } catch (Exception e){
예외 테스트 공부를해놓고 안쓰고있었군요
수정하겠습니다!

2020-02-11 05:12 UTC, yeonnseok commented on src/test/java/StringCalculatorTest/InputValidationTest.java
> +        } catch (Exception e){
네!

2020-02-11 05:43 UTC, yeonnseok commented on src/test/java/StringCalculatorTest/InputValidationTest.java
> +    void validateFirstAndLast(String sourceData, boolean answer) {
테스트에 고려는 안되어있지만 0으로 나누었을 경우 infinite라고 잘 나오는거 같아서.. 
따로 구현하진 않았지만.
아예 0을 예외처리 하는게 나을 까요?

2020-02-11 05:44 UTC, yeonnseok commented on src/main/java/Controller/StringCalculator.java
> +            } catch (Exception e) {
저도 이부분이 마음에 안들긴했는데 리뷰해주신 부분을 잘 이해하지 못했습니다.

`실제 예외가 발생했을 때를 함께 고려하라` 는 말을 어떻게 해석하면 좋을까요?

2020-02-11 05:44 UTC, yeonnseok commented
꼼꼼한 리뷰 정말 감사드립니다.
공부하는데 큰 도움이 되고있습니다!!